### ISSUE TITLE
Request to add marked as done to done.txt

### ISSUE THREAD

**Issue by gitpickles** [drobertadams/todo.txt-cli-addons#2]
Apologies if this is the wrong place to request.

It would be amazing if this addon copied the 'marked as done' task to done.txt

I can see that the repeat script calls the do command of $TODO_SH but the item doesn't land up in done.txt

**Comment by drobertadams** [comment]
Unfortunately, I am no longer actively maintaining this project. However, you can certainly fork the project and do it yourself, or send me a pull request and I'll merge your solution.

**Comment by gitpickles** [comment]
It turns out that request is already included - I just had to amend the script to specify the full path of the todo.sh:

if [[ "$LINE" != "" ]] ; then
    $DO && "$TODO_DIR"/"$TODO_SH" command do "$ITEM"
    $DO && "$TODO_DIR"/"$TODO_SH" command add "$LINE"
fi
